<?php
error_reporting(0);ini_set('display_errors',0);
define('MODULE_DIR','/data/adb/QTUN');define('MODULE_SCRIPTS_DIR','/data/adb/QTUN/scripts');
define('USERS_FILE','/data/adb/php7/files/www/data/users.json');define('TOKENS_FILE','/data/adb/php7/files/www/data/tokens.json');
$api_route=$_GET['api']??$_POST['api']??null;$method=$_SERVER['REQUEST_METHOD'];
function json_response($d){header('Content-Type: application/json; charset=utf-8');echo json_encode($d,JSON_UNESCAPED_UNICODE);exit;}
function get_input(){if($_SERVER['REQUEST_METHOD']==='POST')return json_decode(file_get_contents('php://input'),true)??[];return $_GET;}
function is_api_request(){return isset($_GET['api'])||isset($_POST['api'])||(isset($_SERVER['HTTP_ACCEPT'])&&strpos($_SERVER['HTTP_ACCEPT'],'application/json')!==false);}
function load_users(){if(!file_exists(USERS_FILE)){$du=['admin'=>['password'=>'admin123','role'=>'admin']];file_put_contents(USERS_FILE,json_encode($du,JSON_PRETTY_PRINT));chmod(USERS_FILE,0600);return $du;}return json_decode(file_get_contents(USERS_FILE),true);}
function save_users($u){file_put_contents(USERS_FILE,json_encode($u,JSON_PRETTY_PRINT));chmod(USERS_FILE,0600);}
function verify_user($u,$p){$users=load_users();return isset($users[$u])&&$users[$u]['password']===$p;}
function load_tokens(){if(!file_exists(TOKENS_FILE)){$dir=dirname(TOKENS_FILE);if(!is_dir($dir))mkdir($dir,0755,true);file_put_contents(TOKENS_FILE,json_encode([]));chmod(TOKENS_FILE,0600);return[];}return json_decode(file_get_contents(TOKENS_FILE),true);}
function save_tokens($t){file_put_contents(TOKENS_FILE,json_encode($t));chmod(TOKENS_FILE,0600);}
function generate_token($u){$t=load_tokens();foreach($t as $k=>$v)if($v['username']===$u)unset($t[$k]);$token=bin2hex(random_bytes(32));$t[$token]=['username'=>$u,'expires'=>time()+7*24*3600];save_tokens($t);return $token;}
function verify_token($token){$t=load_tokens();if(isset($t[$token])){$d=$t[$token];if($d['expires']>time())return $d['username'];else{unset($t[$token]);save_tokens($t);}}return false;}
function delete_token($token){$t=load_tokens();if(isset($t[$token])){unset($t[$token]);save_tokens($t);return true;}return false;}
function root_exec($c){$cmd="su -c ".escapeshellarg($c)." 2>&1";exec($cmd,$o,$rc);return['output'=>implode("\n",$o),'code'=>$rc];}
function get_config_dir(){$v1=MODULE_DIR.'/config';$v2=MODULE_DIR.'/libuz';if(is_dir($v1))return$v1;if(is_dir($v2))return$v2;return$v1;}
function qtun_status(){$disable=MODULE_DIR.'/disable';if(file_exists($disable))return['status'=>'Offline','reason'=>'Module disabled'];$pidf=MODULE_DIR.'/run/qtun.pid';if(!file_exists($pidf))return['status'=>'Offline','reason'=>'PID file not found'];$pid=trim(file_get_contents($pidf));if(empty($pid))return['status'=>'Offline','reason'=>'Empty PID'];$res=root_exec("ps -p $pid -o pid= 2>/dev/null");if(trim($res['output'])==='')return['status'=>'Offline','reason'=>'Process not running'];$sf=MODULE_DIR.'/run/status';if(file_exists($sf)){$sc=trim(file_get_contents($sf));if($sc==='running'||$sc==='online')return['status'=>'Online','reason'=>'Status file: '.$sc];}$pc=root_exec("netstat -tulpn 2>/dev/null | grep ':7777' || ss -tulpn 2>/dev/null | grep ':7777'");if(trim($pc['output'])!=='')return['status'=>'Online','reason'=>'Port 7777 listening'];return['status'=>'Online','reason'=>'Process running'];}
function qtun_action($a){switch($a){case'start':$cmd='sh '.MODULE_SCRIPTS_DIR.'/webui.sh start';break;case'stop':$cmd='sh '.MODULE_SCRIPTS_DIR.'/webui.sh stop';break;case'restart':$cmd='sh '.MODULE_SCRIPTS_DIR.'/webui.sh restart';break;default:return['success'=>false,'message'=>'Invalid action'];} $r=root_exec($cmd);sleep(2);$sd=qtun_status();return['success'=>true,'message'=>$r['output']?:'Action completed','status'=>$sd['status'],'reason'=>$sd['reason']];}
function find_log_file(){$paths=[MODULE_DIR.'/run/run.log',MODULE_DIR.'/run/manager.log',MODULE_DIR.'/libuz/run.log','/data/adb/QTUN/run/run.log','/data/adb/QTUN/run/manager.log','/data/adb/QTUN/libuz/run.log','/data/adb/qtun/run/run.log','/data/adb/qtun/run/manager.log','/data/adb/qtun/libuz/run.log'];foreach($paths as $p)if(file_exists($p)&&is_readable($p))return$p;$res=root_exec("find /data/adb -iname 'run.log' -o -iname 'manager.log' 2>/dev/null | head -1");if(!empty(trim($res['output']))){$fp=trim($res['output']);if(file_exists($fp))return$fp;}return null;}
function qtun_logs($lines=50){$f=find_log_file();if(!$f)return "⚠️ Log file not found.\n\n📁 Checked paths:\n".implode("\n",[MODULE_DIR.'/run/run.log',MODULE_DIR.'/run/manager.log','/data/adb/qtun/run/run.log','/data/adb/QTUN/run/run.log']);$c=@file_get_contents($f);if($c===false){$r=root_exec("tail -n $lines ".escapeshellarg($f));if($r['code']===0)return$r['output'];return "⚠️ Cannot read log file: $f\n(Permission denied or file empty)";}$la=explode("\n",$c);$la=array_slice($la,-$lines);return implode("\n",$la);}
function get_active_config(){$paths=[MODULE_DIR.'/config/config.json',MODULE_DIR.'/config/active.json',MODULE_DIR.'/config.json',MODULE_DIR.'/libuz/config.json',MODULE_DIR.'/libuz/active.json','/data/adb/QTUN/config/config.json','/data/adb/QTUN/libuz/config.json'];foreach($paths as $p)if(file_exists($p))return basename($p);$r=root_exec("grep -r 'config' /proc/*/cmdline 2>/dev/null | grep -oE '[a-zA-Z0-9_-]+\.json' | head -1");if(!empty(trim($r['output'])))return trim($r['output']);return null;}
function get_configs(){$cd=get_config_dir();$files=[];$ac=get_active_config();if(is_dir($cd)){$dh=opendir($cd);while(($f=readdir($dh))!==false){if($f==='.'||$f==='..')continue;if($f==='users.json')continue;if(pathinfo($f,PATHINFO_EXTENSION)==='json'){$fp=$cd.'/'.$f;$files[]=['name'=>$f,'size'=>filesize($fp),'modified'=>date('Y-m-d H:i:s',filemtime($fp)),'is_active'=>($ac===$f)];}}closedir($dh);}return$files;}
function read_config($fn){$fn=basename($fn);$cd=get_config_dir();$fp=$cd.'/'.$fn;if(!file_exists($fp))return['success'=>false,'message'=>'File not found'];$ac=get_active_config();return['success'=>true,'content'=>file_get_contents($fp),'is_active'=>($ac===$fn)];}
function create_config($fn,$ct){$fn=basename($fn);if(!preg_match('/^[a-zA-Z0-9_-]+\.json$/',$fn))return['success'=>false,'message'=>'Invalid filename'];if($fn==='users.json')return['success'=>false,'message'=>'Cannot modify users.json'];json_decode($ct);if(json_last_error()!==JSON_ERROR_NONE)return['success'=>false,'message'=>'Invalid JSON: '.json_last_error_msg()];$cd=get_config_dir();if(!is_dir($cd))mkdir($cd,0755,true);$fp=$cd.'/'.$fn;if(file_exists($fp))return['success'=>false,'message'=>'File already exists'];$tmp='/data/local/tmp/qtun_'.$fn;file_put_contents($tmp,$ct);$r=root_exec("cp $tmp $fp && chmod 644 $fp && rm $tmp");if($r['code']!==0){if(file_put_contents($fp,$ct)===false)return['success'=>false,'message'=>'Failed to write file: '.$r['output']];chmod($fp,0644);}return['success'=>true,'message'=>'Config created successfully'];}
function update_config($fn,$ct){$fn=basename($fn);$cd=get_config_dir();$fp=$cd.'/'.$fn;if(!file_exists($fp))return['success'=>false,'message'=>'File not found'];if($fn==='users.json')return['success'=>false,'message'=>'Cannot modify users.json'];$ac=get_active_config();if($ac===$fn)return['success'=>false,'message'=>'Cannot edit config while it is in use by QTUN'];json_decode($ct);if(json_last_error()!==JSON_ERROR_NONE)return['success'=>false,'message'=>'Invalid JSON: '.json_last_error_msg()];$tmp='/data/local/tmp/qtun_'.$fn;file_put_contents($tmp,$ct);$r=root_exec("cp $tmp $fp && chmod 644 $fp && rm $tmp");if($r['code']!==0){if(file_put_contents($fp,$ct)===false)return['success'=>false,'message'=>'Failed to write file: '.$r['output']];chmod($fp,0644);}return['success'=>true,'message'=>'Config updated successfully'];}
function delete_config($fn){$fn=basename($fn);$cd=get_config_dir();$fp=$cd.'/'.$fn;if(!file_exists($fp))return['success'=>false,'message'=>'File not found'];if($fn==='users.json')return['success'=>false,'message'=>'Cannot delete users.json'];$ac=get_active_config();if($ac===$fn)return['success'=>false,'message'=>'Cannot delete config while it is in use by QTUN'];$r=root_exec("rm $fp");if($r['code']!==0)if(!unlink($fp))return['success'=>false,'message'=>'Failed to delete file'];return['success'=>true,'message'=>'Config deleted successfully'];}
if(is_api_request()){
    if($api_route==='login'){if($method!=='POST')json_response(['success'=>false,'message'=>'Method not allowed']);$in=get_input();if(!$in||!isset($in['username'])||!isset($in['password']))json_response(['success'=>false,'message'=>'Username and password required']);$u=trim($in['username']);$p=$in['password'];if(verify_user($u,$p)){$token=generate_token($u);json_response(['success'=>true,'username'=>$u,'token'=>$token]);}else json_response(['success'=>false,'message'=>'Invalid username or password']);}
    elseif($api_route==='verify_token'){if($method!=='POST')json_response(['success'=>false,'message'=>'Method not allowed']);$in=get_input();if(!isset($in['token']))json_response(['success'=>false,'message'=>'Token required']);$uname=verify_token($in['token']);if($uname)json_response(['success'=>true,'username'=>$uname]);else json_response(['success'=>false,'message'=>'Invalid or expired token']);}
    elseif($api_route==='logout'){if($method!=='POST')json_response(['success'=>false,'message'=>'Method not allowed']);$in=get_input();if(isset($in['token']))delete_token($in['token']);json_response(['success'=>true,'message'=>'Logged out']);}
    elseif($api_route==='status'){if($method!=='GET')json_response(['success'=>false,'message'=>'Method not allowed']);$sd=qtun_status();json_response(['success'=>true,'status'=>$sd['status'],'reason'=>$sd['reason']]);}
    elseif($api_route==='action'){if($method!=='POST')json_response(['success'=>false,'message'=>'Method not allowed']);$in=get_input();if(!$in||!isset($in['action']))json_response(['success'=>false,'message'=>'Action required']);json_response(qtun_action($in['action']));}
    elseif($api_route==='logs'){if($method==='GET')$lines=isset($_GET['lines'])?intval($_GET['lines']):100;elseif($method==='POST'){$in=get_input();$lines=isset($in['lines'])?intval($in['lines']):100;}else json_response(['success'=>false,'message'=>'Method not allowed']);$lines=max(1,min(500,$lines));$log=qtun_logs($lines);json_response(['success'=>true,'logs'=>$log]);}
    elseif($api_route==='host'){$host=$_SERVER['HTTP_HOST']??'localhost';$h=explode(':',$host)[0];json_response(['success'=>true,'host'=>$h]);}
    elseif($api_route==='configs'){if($method==='GET'){if(isset($_GET['action'])&&$_GET['action']==='list')json_response(['success'=>true,'configs'=>get_configs()]);if(isset($_GET['file'])){$fn=basename($_GET['file']);$cd=get_config_dir();$fp=$cd.'/'.$fn;if(!file_exists($fp))json_response(['success'=>false,'message'=>'File not found: '.$fn]);$ct=file_get_contents($fp);$ac=get_active_config();json_response(['success'=>true,'filename'=>$fn,'content'=>$ct,'size'=>filesize($fp),'modified'=>date('Y-m-d H:i:s',filemtime($fp)),'is_active'=>($ac===$fn)]);}json_response(['success'=>true,'configs'=>get_configs()]);}elseif($method==='POST'){$in=get_input();if(!isset($in['action']))json_response(['success'=>false,'message'=>'Action required']);switch($in['action']){case'create':if(!isset($in['filename'])||!isset($in['content']))json_response(['success'=>false,'message'=>'Filename and content required']);json_response(create_config($in['filename'],$in['content']));break;case'edit':if(!isset($in['filename'])||!isset($in['content']))json_response(['success'=>false,'message'=>'Filename and content required']);json_response(update_config($in['filename'],$in['content']));break;case'delete':if(!isset($in['filename']))json_response(['success'=>false,'message'=>'Filename required']);json_response(delete_config($in['filename']));break;case'read':if(!isset($in['filename']))json_response(['success'=>false,'message'=>'Filename required']);json_response(read_config($in['filename']));break;default:json_response(['success'=>false,'message'=>'Invalid action']);}}json_response(['success'=>false,'message'=>'Method not allowed']);}
    elseif($api_route==='users'){if($method==='GET'){$users=load_users();$ul=[];foreach($users as $u=>$d)$ul[]=['username'=>$u,'role'=>$d['role']];json_response(['success'=>true,'users'=>$ul]);}elseif($method==='POST'){$in=get_input();if(!isset($in['action']))json_response(['success'=>false,'message'=>'Action required']);$users=load_users();switch($in['action']){case'add':if(!isset($in['username'])||!isset($in['password']))json_response(['success'=>false,'message'=>'Username and password required']);$u=trim($in['username']);$p=$in['password'];if(empty($u)||empty($p))json_response(['success'=>false,'message'=>'Username and password cannot be empty']);if(isset($users[$u]))json_response(['success'=>false,'message'=>'User already exists']);if(strlen($p)<6)json_response(['success'=>false,'message'=>'Password must be at least 6 characters']);$users[$u]=['password'=>$p,'role'=>'user'];save_users($users);json_response(['success'=>true,'message'=>'User added successfully']);break;case'delete':if(!isset($in['username']))json_response(['success'=>false,'message'=>'Username required']);$u=trim($in['username']);if($u==='admin')json_response(['success'=>false,'message'=>'Cannot delete admin user']);if(!isset($users[$u]))json_response(['success'=>false,'message'=>'User not found']);unset($users[$u]);save_users($users);json_response(['success'=>true,'message'=>'User deleted successfully']);break;case'changepass':if(!isset($in['username'])||!isset($in['old_password'])||!isset($in['new_password']))json_response(['success'=>false,'message'=>'Username, old password and new password required']);$u=trim($in['username']);if(!isset($users[$u]))json_response(['success'=>false,'message'=>'User not found']);if($users[$u]['password']!==$in['old_password'])json_response(['success'=>false,'message'=>'Old password is incorrect']);if(strlen($in['new_password'])<6)json_response(['success'=>false,'message'=>'New password must be at least 6 characters']);$users[$u]['password']=$in['new_password'];save_users($users);json_response(['success'=>true,'message'=>'Password changed successfully']);break;default:json_response(['success'=>false,'message'=>'Invalid action']);}}json_response(['success'=>false,'message'=>'Method not allowed']);}
    json_response(['success'=>false,'message'=>'Unknown API endpoint']);
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>QTUN Manager</title>
    <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css" rel="stylesheet">
    <link href="/bootstrap/animate/animate.min.css" rel="stylesheet">
    <style>
        .page{display:none!important}.page.active{display:block!important}body{min-height:100vh;background-color:#f8f9fa}.sidebar{position:fixed;top:0;bottom:0;left:0;z-index:100;padding:48px 0 0;box-shadow:inset -1px 0 0 rgba(0,0,0,.1)}.sidebar .nav-link{font-weight:500;color:#333;transition:all 0.2s}.sidebar .nav-link.active{color:#0d6efd;background:#e7f1ff;border-radius:.25rem}.sidebar .nav-link:hover{color:#0d6efd;background:#f0f4ff}@media (max-width:767.98px){.sidebar{position:fixed;top:0;bottom:0;left:-100%;transition:left 0.3s;z-index:1040;width:250px;background:white;box-shadow:2px 0 5px rgba(0,0,0,0.2)}.sidebar.show{left:0}.sidebar-backdrop{position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(0,0,0,.5);z-index:1030;display:none}.sidebar-backdrop.show{display:block}}main{padding-top:1.5rem}.navbar-brand{padding-top:.75rem;padding-bottom:.75rem;font-size:1.25rem;font-weight:600}.status-dot{width:12px;height:12px;border-radius:50%;display:inline-block;margin-right:8px;animation:pulse 2s infinite}@keyframes pulse{0%,100%{opacity:1}50%{opacity:.5}}.log-container{background:#1e1e1e;color:#d4d4d4;font-family:'Courier New',monospace;font-size:.8rem;max-height:400px;overflow-y:auto;padding:1rem;border-radius:.375rem;white-space:pre-wrap;word-wrap:break-word}.config-item{cursor:pointer;transition:all 0.15s ease-in-out}.config-item:hover{background-color:#f0f4ff;transform:translateX(4px)}.config-item.active{background-color:#e7f1ff;border-color:#0d6efd}.editor-info{display:none;background-color:#fff3cd;border:1px solid #ffeaa7;color:#856404;padding:.75rem;border-radius:.375rem;margin-bottom:1rem}.editor-info.show{display:block}.clash-topbar{position:fixed;top:0;left:0;right:0;height:48px;background:#fff;z-index:1050;box-shadow:0 1px 3px rgba(0,0,0,.1);display:none}.clash-topbar.show{display:flex;align-items:center;padding:0 1rem}.clash-frame{position:fixed;top:48px;left:0;right:0;bottom:0;border:none;width:100%;height:calc(100% - 48px)}.btn-loading{pointer-events:none;opacity:0.8}.btn-loading .btn-text{display:none}.btn-loading .spinner{display:inline-block}.spinner{display:none}.card{animation:animate__fadeInUp;animation-duration:0.5s}.animate__animated.animate__faster{animation-duration:0.3s}
    </style>
</head>
<body>
    <nav class="navbar navbar-light bg-white shadow-sm sticky-top d-md-none d-none" id="topNavbar">
        <div class="container-fluid"><button class="navbar-toggler" type="button" id="sidebarToggle"><span class="navbar-toggler-icon"></span></button><span class="navbar-brand mb-0 h1">QTUN Manager</span></div>
    </nav>
    <div class="sidebar-backdrop" id="sidebarBackdrop"></div>
    <div class="clash-topbar" id="clashTopbar">
        <button class="btn btn-sm btn-outline-secondary me-3" id="clashBackBtn"><i class="bi bi-arrow-left"></i> Back</button>
        <span class="fw-bold">Clash Dashboard</span>
        <button class="btn btn-sm btn-outline-secondary ms-auto" onclick="reloadClashUI()"><i class="bi bi-arrow-clockwise"></i></button>
    </div>
    <div class="container-fluid"><div class="row">
        <nav class="col-md-3 col-lg-2 d-md-block bg-white sidebar d-none" id="sidebarMenu">
            <div class="position-sticky pt-3">
                <div class="d-flex align-items-center justify-content-between px-3 mb-3"><span class="navbar-brand h4 mb-0">QTUN</span><button class="btn btn-close d-md-none" id="sidebarClose"></button></div>
                <ul class="nav flex-column">
                    <li class="nav-item"><a class="nav-link active" href="#" data-page="dashboard"><i class="bi bi-speedometer2 me-2"></i> Dashboard</a></li>
                    <li class="nav-item"><a class="nav-link" href="#" data-page="configs"><i class="bi bi-file-earmark-code me-2"></i> Configs</a></li>
                    <li class="nav-item"><a class="nav-link" href="#" data-page="clash"><i class="bi bi-diagram-3 me-2"></i> Clash</a></li>
                    <li class="nav-item"><a class="nav-link" href="#" data-page="users"><i class="bi bi-people me-2"></i> Users</a></li>
                    <li class="nav-item mt-4"><a class="nav-link text-danger" href="#" id="logoutBtn"><i class="bi bi-box-arrow-right me-2"></i> Logout</a></li>
                </ul>
            </div>
        </nav>
        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4" id="mainContent">
            <div class="page active animate__animated animate__fadeIn" id="page-login">
                <div class="row justify-content-center mt-5"><div class="col-md-5 col-lg-4"><div class="text-center mb-4"><h1 class="fw-bold text-primary animate__animated animate__bounceIn">QTUN</h1><p class="text-muted">Tunneling Control Panel</p></div>
                <div class="card shadow"><div class="card-body"><h5 class="card-title mb-4">Sign In</h5><div id="login-error" class="alert alert-danger d-none"></div>
                <div class="mb-3"><label class="form-label">Username</label><input type="text" class="form-control" id="login-username" placeholder="Enter username" autofocus></div>
                <div class="mb-3"><label class="form-label">Password</label><input type="password" class="form-control" id="login-password" placeholder="Enter password" onkeypress="if(event.key==='Enter')doLogin()"></div>
                <button class="btn btn-primary w-100" onclick="doLogin()" id="loginBtn">Sign In</button></div></div></div></div>
            </div>
            <div class="page" id="page-dashboard">
                <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom animate__animated animate__fadeInDown"><h1 class="h2">Dashboard</h1></div>
                <div class="row"><div class="col-md-4 mb-4"><div class="card border-0 shadow-sm animate__animated animate__fadeInLeft"><div class="card-body"><h6 class="card-title text-uppercase text-muted mb-3">Service Status</h6><div class="d-flex align-items-center"><span class="status-dot bg-secondary" id="status-dot"></span><div><h4 class="mb-0" id="status-text">--</h4><small class="text-muted" id="status-reason"></small></div></div></div></div></div>
                <div class="col-md-8 mb-4"><div class="card border-0 shadow-sm animate__animated animate__fadeInRight"><div class="card-body"><h6 class="card-title text-uppercase text-muted mb-3">Quick Actions</h6><div class="d-flex gap-2 flex-wrap">
                    <button class="btn btn-outline-primary" id="btn-start" onclick="confirmAction('Start QTUN service?',()=>doAction('start'))"><span class="btn-text"><i class="bi bi-play-fill"></i> Start</span><span class="spinner spinner-border spinner-border-sm"></span></button>
                    <button class="btn btn-outline-danger" id="btn-stop" onclick="confirmAction('Stop QTUN service?',()=>doAction('stop'))"><span class="btn-text"><i class="bi bi-stop-fill"></i> Stop</span><span class="spinner spinner-border spinner-border-sm"></span></button>
                    <button class="btn btn-outline-secondary" id="btn-restart" onclick="confirmAction('Restart QTUN service?',()=>doAction('restart'))"><span class="btn-text"><i class="bi bi-arrow-repeat"></i> Restart</span><span class="spinner spinner-border spinner-border-sm"></span></button>
                </div></div></div></div></div>
                <div class="card border-0 shadow-sm animate__animated animate__fadeInUp"><div class="card-body"><div class="d-flex justify-content-between align-items-center mb-3"><h6 class="card-title text-uppercase text-muted mb-0">Live Logs</h6><span class="badge bg-success">Auto Refresh</span></div><div id="log-error" class="alert alert-info d-none"></div><div class="log-container" id="log-content">Connecting to log file...</div></div></div>
            </div>
            <div class="page" id="page-configs">
                <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom animate__animated animate__fadeInDown"><h1 class="h2">Configuration</h1></div>
                <div class="row"><div class="col-lg-4 mb-4"><div class="card border-0 shadow-sm animate__animated animate__fadeInLeft"><div class="card-body"><div class="d-flex justify-content-between align-items-center mb-3"><h6 class="card-title text-uppercase text-muted mb-0">Config Files</h6><button class="btn btn-primary btn-sm" onclick="openCreateModal()"><i class="bi bi-plus-lg"></i> New</button></div><div id="configs-error" class="alert alert-danger d-none"></div><div id="configs-success" class="alert alert-success d-none"></div><div id="configs-list"></div></div></div></div>
                <div class="col-lg-8"><div class="card border-0 shadow-sm animate__animated animate__fadeInRight"><div class="card-body"><div id="editor-info" class="editor-info"><i class="bi bi-exclamation-triangle me-2"></i> Config is currently in use by QTUN. Stop the service to edit or delete.</div><div class="d-flex justify-content-between align-items-center mb-3"><h6 class="card-title text-uppercase text-muted mb-0" id="editor-title">Select a config file</h6><div id="editor-actions" style="display:none"><button class="btn btn-success btn-sm" id="btn-save-config" onclick="saveCurrentConfig()"><span class="btn-text"><i class="bi bi-check-lg"></i> Save</span><span class="spinner spinner-border spinner-border-sm"></span></button><button class="btn btn-outline-secondary btn-sm" onclick="reloadCurrentConfig()">Reload</button><button class="btn btn-danger btn-sm" id="btn-delete-config" onclick="deleteCurrentConfig()"><span class="btn-text"><i class="bi bi-trash"></i> Delete</span><span class="spinner spinner-border spinner-border-sm"></span></button></div></div><div id="editor-error" class="alert alert-danger d-none"></div><textarea class="form-control" id="config-editor" rows="20" placeholder="Select a configuration file from the list..." disabled></textarea></div></div></div></div>
            </div>
            <div class="page" id="page-clash">
                <div id="clash-container"></div>
            </div>
            <div class="page" id="page-users">
                <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom animate__animated animate__fadeInDown"><h1 class="h2">User Management</h1></div>
                <div class="row"><div class="col-lg-6 mb-4"><div class="card border-0 shadow-sm h-100 animate__animated animate__fadeInLeft"><div class="card-body"><h6 class="card-title text-uppercase text-muted mb-3">User List</h6><div id="users-list"></div></div></div></div>
                <div class="col-lg-6"><div class="card border-0 shadow-sm mb-4 animate__animated animate__fadeInRight"><div class="card-body"><h6 class="card-title text-uppercase text-muted mb-3">Add User</h6><div id="users-error" class="alert alert-danger d-none"></div><div id="users-success" class="alert alert-success d-none"></div><div class="mb-3"><label class="form-label">Username</label><input type="text" class="form-control" id="new-username" placeholder="Enter username"></div><div class="mb-3"><label class="form-label">Password</label><input type="password" class="form-control" id="new-password" placeholder="Min 6 characters"></div><button class="btn btn-primary" onclick="addUser()" id="btn-add-user"><span class="btn-text">Add User</span><span class="spinner spinner-border spinner-border-sm"></span></button></div></div>
                <div class="card border-0 shadow-sm animate__animated animate__fadeInUp"><div class="card-body"><h6 class="card-title text-uppercase text-muted mb-3">Change Password</h6><div class="mb-3"><label class="form-label">Current Password</label><input type="password" class="form-control" id="old-pass" placeholder="Enter current password"></div><div class="mb-3"><label class="form-label">New Password</label><input type="password" class="form-control" id="new-pass" placeholder="Min 6 characters"></div><button class="btn btn-warning" onclick="changePassword()" id="btn-change-pass"><span class="btn-text">Update Password</span><span class="spinner spinner-border spinner-border-sm"></span></button></div></div></div></div>
            </div>
        </main>
    </div></div>
    <div class="modal fade" id="confirm-action-modal" tabindex="-1">
        <div class="modal-dialog modal-dialog-centered modal-sm"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Confirm</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><p id="confirm-action-message"></p></div><div class="modal-footer"><button class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button><button class="btn btn-danger" id="confirm-action-ok">OK</button></div></div></div>
    </div>
    <div class="modal fade" id="delete-modal" tabindex="-1">
        <div class="modal-dialog modal-dialog-centered modal-sm"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Confirm Delete</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><p>Delete <strong id="delete-filename"></strong>?</p><small class="text-danger">This action cannot be undone.</small></div><div class="modal-footer"><button class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button><button class="btn btn-danger" id="confirm-delete-btn">Delete</button></div></div></div>
    </div>
    <div class="modal fade" id="create-modal" tabindex="-1">
        <div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">New Configuration</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div id="create-error" class="alert alert-danger d-none"></div><label class="form-label">Filename</label><input type="text" class="form-control" id="new-filename" placeholder="example.json"><small class="text-muted">Only a-z, 0-9, _, - allowed. Must end with .json</small></div><div class="modal-footer"><button class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary" onclick="createNewConfig()" id="btn-create-config">Create</button></div></div></div>
    </div>
    <script src="/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script>
        let currentUser=null,currentConfigFile=null,isConfigActive=!1,refreshLogInterval=null,refreshStatusInterval=null;
        let bootstrapModals={createModal:null,deleteModal:null,confirmModal:null};
        const TOKEN_KEY='qtun_auth_token';
        function saveToken(e){localStorage.setItem(TOKEN_KEY,e)}
        function getToken(){return localStorage.getItem(TOKEN_KEY)}
        function clearToken(){localStorage.removeItem(TOKEN_KEY)}
        function enforcePageVisibility(){document.querySelectorAll('.page').forEach(e=>{e.style.display=e.classList.contains('active')?'block':'none'})}
        function autoLogin(){const e=getToken();if(!e){enforcePageVisibility();document.getElementById('login-username').focus();return}
            apiCall('verify_token',{token:e},t=>{
                if(t.success){currentUser=t.username;document.getElementById('page-login').classList.remove('active');document.getElementById('sidebarMenu').classList.remove('d-none');document.getElementById('topNavbar').classList.remove('d-none');showPage('dashboard')}
                else{clearToken();enforcePageVisibility();document.getElementById('sidebarBackdrop').classList.remove('show')}
                enforcePageVisibility()
            },true)}
        function initSidebar(){const e=document.getElementById('sidebarMenu'),t=document.getElementById('sidebarBackdrop'),n=document.getElementById('sidebarToggle'),o=document.getElementById('sidebarClose');function s(){e.classList.add('show'),t.classList.add('show')}function a(){e.classList.remove('show'),t.classList.remove('show')}n&&n.addEventListener('click',s),o&&o.addEventListener('click',a),t&&t.addEventListener('click',a);document.querySelectorAll('#sidebarMenu .nav-link[data-page]').forEach(e=>{e.addEventListener('click',()=>{window.innerWidth<768&&a()})})}
        function enterFullscreenClash(){document.getElementById('sidebarMenu').classList.add('d-none');document.getElementById('topNavbar').classList.add('d-none');document.getElementById('mainContent').classList.add('d-none');document.getElementById('clashTopbar').classList.add('show')}
        function exitFullscreenClash(){document.getElementById('sidebarMenu').classList.remove('d-none');document.getElementById('topNavbar').classList.remove('d-none');document.getElementById('mainContent').classList.remove('d-none');document.getElementById('clashTopbar').classList.remove('show');document.getElementById('sidebarBackdrop').classList.remove('show');const e=document.querySelector('.clash-frame');e&&e.remove()}
        function showPage(e){if('dashboard'!==e&&(refreshLogInterval&&clearInterval(refreshLogInterval),refreshStatusInterval&&clearInterval(refreshStatusInterval)),e==='clash'){enterFullscreenClash();reloadClashUI();return}else{exitFullscreenClash()}document.querySelectorAll('.page').forEach(e=>{e.classList.remove('active'),e.style.display='none'});const t=document.getElementById('page-'+e);t&&(t.classList.add('active'),t.style.display='block');document.querySelectorAll('#sidebarMenu .nav-link').forEach(t=>{t.classList.remove('active'),t.dataset.page===e&&t.classList.add('active')});'dashboard'===e?(refreshStatus(),refreshLogs(),refreshStatusInterval=setInterval(refreshStatus,5e3),refreshLogInterval=setInterval(refreshLogs,3e3)):'configs'===e?refreshConfigList():'users'===e&&refreshUserList()}
        function doLogin(){const e=document.getElementById('login-username').value.trim(),t=document.getElementById('login-password').value;if(!e||!t)return showAlert('login-error','Username and password required','danger');const n=document.getElementById('loginBtn');setBtnLoading(n,!0);apiCall('login',{username:e,password:t},o=>{setBtnLoading(n,!1);if(o.success){currentUser=o.username;saveToken(o.token);document.getElementById('page-login').classList.remove('active');document.getElementById('sidebarMenu').classList.remove('d-none');document.getElementById('topNavbar').classList.remove('d-none');showPage('dashboard')}else showAlert('login-error',o.message||'Login failed','danger');enforcePageVisibility()})}
        function logout(){confirmAction('Logout?',()=>{const e=getToken();e&&apiCall('logout',{token:e},()=>{});clearToken();currentUser=null;refreshLogInterval&&clearInterval(refreshLogInterval);refreshStatusInterval&&clearInterval(refreshStatusInterval);exitFullscreenClash();document.querySelectorAll('.modal.show').forEach(e=>{bootstrap.Modal.getInstance(e)?.hide()});document.querySelectorAll('.page').forEach(e=>{e.classList.remove('active'),e.style.display='none'});document.getElementById('page-login').classList.add('active');document.getElementById('page-login').style.display='block';document.getElementById('sidebarMenu').classList.add('d-none');document.getElementById('topNavbar').classList.add('d-none');document.getElementById('login-username').value='';document.getElementById('login-password').value='';document.getElementById('sidebarBackdrop').classList.remove('show')})}
        function confirmAction(e,t){document.getElementById('confirm-action-message').textContent=e;const n=document.getElementById('confirm-action-ok');n.onclick=()=>{bootstrapModals.confirmModal.hide();t()};bootstrapModals.confirmModal.show()}
        function setBtnLoading(e,t){if(!e)return;if(t){e.classList.add('btn-loading');e.disabled=!0}else{e.classList.remove('btn-loading');e.disabled=!1}}
        function apiCall(e,t,n,keepTokenOnError=false){let o=window.location.href.split('?')[0],s='';e.includes('?')&&([e,s]=e.split('?'),s='&'+s),o+='?api='+e+s;const a={method:t?'POST':'GET',headers:{'Content-Type':'application/json',Accept:'application/json'}};t&&(a.body=JSON.stringify(t));fetch(o,a).then(e=>e.json()).then(e=>n(e)).catch(e=>{if(!keepTokenOnError)n({success:!1,message:'Network error'});else console.error('Token verify network error')})}
        function showAlert(e,t,n='danger'){const o=document.getElementById(e);o&&(o.textContent=t,o.className='alert alert-'+n,o.classList.remove('d-none'),setTimeout(()=>o.classList.add('d-none'),5e3))}
        function refreshStatus(){apiCall('status',null,e=>{if(e.success){const t=document.getElementById('status-dot'),n=document.getElementById('status-text'),o=document.getElementById('status-reason');t.className='status-dot '+(e.status==='Online'?'bg-success':'bg-secondary');n.textContent=e.status;o.textContent=e.reason}})}
        function refreshLogs(){apiCall('logs',{lines:100},e=>{if(e.success){const t=document.getElementById('log-content');t.textContent=e.logs;t.scrollTop=t.scrollHeight}else document.getElementById('log-error').textContent=e.message,document.getElementById('log-error').classList.remove('d-none')})}
        function doAction(e){const t=document.getElementById('btn-'+e);setBtnLoading(t,!0);apiCall('action',{action:e},n=>{setBtnLoading(t,!1);n.success&&(refreshStatus(),refreshLogs())})}
        function refreshConfigList(){apiCall('configs',null,e=>{if(e.success){const t=document.getElementById('configs-list');t.innerHTML='';if(0===e.configs.length)return void(t.innerHTML='<p class="text-muted">No config files found</p>');e.configs.forEach(e=>{const n=document.createElement('div');n.className='list-group-item config-item d-flex justify-content-between align-items-center';n.onclick=()=>selectConfig(e.name);n.innerHTML=`<div><strong>${e.name}</strong>${e.is_active?' <span class="badge bg-warning ms-2">IN USE</span>':''}<br><small class="text-muted">${Math.round(e.size/1024)} KB &middot; ${e.modified}</small></div>`;t.appendChild(n)})}})}
        function selectConfig(e){currentConfigFile=e;document.querySelectorAll('.config-item').forEach(e=>e.classList.remove('active'));event.currentTarget.classList.add('active');document.getElementById('editor-title').textContent=e;document.getElementById('editor-actions').style.display='';apiCall('configs',{action:'read',filename:e},t=>{if(t.success){isConfigActive=t.is_active;document.getElementById('config-editor').value=t.content;document.getElementById('config-editor').disabled=isConfigActive;document.getElementById('btn-save-config').disabled=isConfigActive;document.getElementById('btn-delete-config').disabled=isConfigActive;isConfigActive?document.getElementById('editor-info').classList.add('show'):document.getElementById('editor-info').classList.remove('show')}else showAlert('editor-error',t.message,'danger')})}
        function saveCurrentConfig(){if(currentConfigFile&&!isConfigActive){const e=document.getElementById('config-editor').value,t=document.getElementById('btn-save-config');setBtnLoading(t,!0);apiCall('configs',{action:'edit',filename:currentConfigFile,content:e},n=>{setBtnLoading(t,!1);n.success?(showAlert('configs-success',n.message,'success'),refreshConfigList()):showAlert('editor-error',n.message,'danger')})}}
        function reloadCurrentConfig(){currentConfigFile&&selectConfig(currentConfigFile)}
        function deleteCurrentConfig(){if(!currentConfigFile||isConfigActive)return showAlert('editor-error','Cannot delete active config','warning');document.getElementById('delete-filename').textContent=currentConfigFile;document.getElementById('confirm-delete-btn').onclick=()=>{const e=document.getElementById('confirm-delete-btn');setBtnLoading(e,!0);apiCall('configs',{action:'delete',filename:currentConfigFile},t=>{setBtnLoading(e,!1);if(t.success){bootstrapModals.deleteModal.hide();refreshConfigList();currentConfigFile=null;isConfigActive=!1;document.getElementById('editor-title').textContent='Select a config file';document.getElementById('editor-actions').style.display='none';document.getElementById('config-editor').value='';document.getElementById('config-editor').disabled=!0;document.getElementById('editor-info').classList.remove('show');showAlert('configs-success','Config deleted','success')}else showAlert('configs-error',t.message,'danger')})};bootstrapModals.deleteModal.show()}
        function openCreateModal(){bootstrapModals.createModal.show()}
        function createNewConfig(){const e=document.getElementById('new-filename').value.trim();if(!e)return showAlert('create-error','Filename required','danger');const t=JSON.stringify({example:'value'},null,2),n=document.getElementById('btn-create-config');setBtnLoading(n,!0);apiCall('configs',{action:'create',filename:e,content:t},o=>{setBtnLoading(n,!1);o.success?(bootstrapModals.createModal.hide(),document.getElementById('new-filename').value='',refreshConfigList(),showAlert('configs-success',o.message,'success')):showAlert('create-error',o.message,'danger')})}
        function reloadClashUI(){const e=document.querySelector('.clash-frame');e&&e.remove();const t=document.createElement('iframe');t.className='clash-frame';t.src='about:blank';document.body.appendChild(t);apiCall('host',null,n=>{if(n.success){const o='http://'+n.host+':9090/ui';t.src=o}else{t.remove();const e=document.getElementById('clash-container');e.innerHTML='<p class="text-danger">Failed to load Clash Dashboard.</p>'}})}
        function refreshUserList(){apiCall('users',null,e=>{if(e.success){const t=document.getElementById('users-list');t.innerHTML='';e.users.forEach(e=>{const n=document.createElement('div');n.className='d-flex align-items-center justify-content-between mb-2 p-2 bg-light rounded';n.innerHTML=`<span><strong>${e.username}</strong> <span class="badge ${e.role==='admin'?'bg-danger':'bg-primary'}">${e.role}</span></span>${e.username!=='admin'?`<button class="btn btn-sm btn-outline-danger" onclick="deleteUser('${e.username}')"><i class="bi bi-x"></i></button>`:''}`;t.appendChild(n)})}})}
        function addUser(){const e=document.getElementById('new-username').value.trim(),t=document.getElementById('new-password').value;if(!e||!t)return showAlert('users-error','Username and password required','danger');const n=document.getElementById('btn-add-user');setBtnLoading(n,!0);apiCall('users',{action:'add',username:e,password:t},o=>{setBtnLoading(n,!1);o.success?(document.getElementById('new-username').value='',document.getElementById('new-password').value='',refreshUserList(),showAlert('users-success',o.message,'success')):showAlert('users-error',o.message,'danger')})}
        function deleteUser(e){confirmAction(`Delete user ${e}?`,()=>{apiCall('users',{action:'delete',username:e},t=>{t.success?(refreshUserList(),showAlert('users-success',t.message,'success')):showAlert('users-error',t.message,'danger')})})}
        function changePassword(){const e=document.getElementById('old-pass').value,t=document.getElementById('new-pass').value;if(!e||!t)return showAlert('users-error','Old and new password required','danger');const n=document.getElementById('btn-change-pass');setBtnLoading(n,!0);apiCall('users',{action:'changepass',username:currentUser,old_password:e,new_password:t},o=>{setBtnLoading(n,!1);o.success?(document.getElementById('old-pass').value='',document.getElementById('new-pass').value='',showAlert('users-success',o.message,'success')):showAlert('users-error',o.message,'danger')})}
        document.addEventListener('DOMContentLoaded',()=>{
            bootstrapModals.createModal=new bootstrap.Modal(document.getElementById('create-modal'));
            bootstrapModals.deleteModal=new bootstrap.Modal(document.getElementById('delete-modal'));
            bootstrapModals.confirmModal=new bootstrap.Modal(document.getElementById('confirm-action-modal'));
            initSidebar();
            document.querySelectorAll('#sidebarMenu .nav-link[data-page]').forEach(e=>{e.addEventListener('click',t=>{t.preventDefault();const n=e.dataset.page;n&&showPage(n)})});
            document.getElementById('logoutBtn').addEventListener('click',e=>{e.preventDefault();logout()});
            document.getElementById('clashBackBtn').addEventListener('click',()=>{showPage('dashboard')});
            enforcePageVisibility();
            autoLogin();
            if(!getToken()) document.getElementById('login-username').focus();
        });
    </script>
</body>
</html>